<a href="https://colab.research.google.com/github/Ravinangal/colabgoogle/blob/main/read_write_numpy_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([5,6,7,8])
print(a)
b = np.array([1,2,3,4])
print(b)
print("---------------------")
sum = a + b
print(sum)

print("---------------------")
c = np.array([[5,6],[6,8]])
print(c)

[5 6 7 8]
[1 2 3 4]
---------------------
[ 6  8 10 12]
---------------------
[[5 6]
 [6 8]]


In [ ]:
import numpy as np
c = np.array([[5,6],[6,8]])
x = np.array([2,3])

sum = c + x
mul = c * x
print(sum)
print(mul)





[[ 7  9]
 [ 8 11]]
[[10 18]
 [12 24]]


In [2]:
p = [5,7]
q = [7]
sum = p+q
print(sum)

[5, 7, 7]


In [4]:
import pandas as pd
employee = {"name":["ak","pk","sk"],
            "salary":[50000,60000,70000],
            "designer":["one","two","three"]}

df =pd.DataFrame(employee)
print(df)

  name  salary designer
0   ak   50000      one
1   pk   60000      two
2   sk   70000    three
